### PR TITLE
Update command.txt

### PR DESCRIPTION
**Pull request by amoghak-ds**
Fixed Typos

### CODE REVIEW

**Comment by danielmarv** [comment]
please ty to request reviews on opening PR @amoghak-ds

**Comment by amoghak-ds** [comment]
Alright will do that from the next one. Do I need to do it before submitting the PR?

**Comment by danielmarv** [comment]
Even on his u need to put reviewers

**Review by richarddushime — APPROVED** [review]
Thanks @amoghak-ds

**Pull request merged**
